// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_gIwQKwlprhCvc9fEK0BSiiAu0f-jnA',
    appId: '1:792481109924:web:1c1551dac19ff1a77bd331',
    messagingSenderId: '792481109924',
    projectId: 'caffeto-a12fe',
    authDomain: 'caffeto-a12fe.firebaseapp.com',
    storageBucket: 'caffeto-a12fe.firebasestorage.app',
    measurementId: 'G-33XQ6JGLZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcyTvBmAkL4-nYsYaw87N3E1hv0taxmuI',
    appId: '1:792481109924:android:b259d84725327f317bd331',
    messagingSenderId: '792481109924',
    projectId: 'caffeto-a12fe',
    storageBucket: 'caffeto-a12fe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcdeia20UOGbOK5f8eKYkFMuS-TdbCK8',
    appId: '1:792481109924:ios:7d8b9ee375ed40ef7bd331',
    messagingSenderId: '792481109924',
    projectId: 'caffeto-a12fe',
    storageBucket: 'caffeto-a12fe.firebasestorage.app',
    iosBundleId: 'com.example.caffeto',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcdeia20UOGbOK5f8eKYkFMuS-TdbCK8',
    appId: '1:792481109924:ios:7d8b9ee375ed40ef7bd331',
    messagingSenderId: '792481109924',
    projectId: 'caffeto-a12fe',
    storageBucket: 'caffeto-a12fe.firebasestorage.app',
    iosBundleId: 'com.example.caffeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_gIwQKwlprhCvc9fEK0BSiiAu0f-jnA',
    appId: '1:792481109924:web:cd9f1b0ba9ef4dd17bd331',
    messagingSenderId: '792481109924',
    projectId: 'caffeto-a12fe',
    authDomain: 'caffeto-a12fe.firebaseapp.com',
    storageBucket: 'caffeto-a12fe.firebasestorage.app',
    measurementId: 'G-3MPEGJYFWE',
  );
}
